#pragma once
#include <string>
#include <iostream>
#include "team.hpp"
using namespace std;

class Game
{
    /**
     * @brief this class represent a game between 2 basketball teams.
     * the points of each team determin in the folowing way:
     * - the home team poinst is generated by normal distribution where the mean is 77.5 and the stdv is 5.625
     * - the away team poinst is generated by normal distribution where the mean is 75.0 and the stdv is 6.25
     * - each team get more points according to their talent, the claculation is team.talent*10.
     * each game have the following fields in it:
     * home - a pointer to the home team in this match
     * away - a pointer to the away team in this match 
     * start - says if the game has started (and over) yet
     * winner - a pointer to the team who won the game.
     * loser - a pointer to the team who lost the game.
     * home score - the score of the home team in this match.
     * away score - the score of the away team in this match.
     * 
     */
private:
    Team *_home = nullptr;
    Team *_away = nullptr;
    bool _start = false;
    Team *_winner = nullptr;
    Team *_loser = nullptr;
    int _home_score = 0;
    int _away_score = 0;

public:
    Team *&getHomeTeam() { return this->_home; }
    Team *&getAwayTeam() { return this->_away; }
    int &getHomeScore();
    int &getAwayScore();
    Team *&getWinner();
    Team *&getLoser();

    Game(Team &home, Team &away);
    void play();
    friend std::ostream &operator<<(std::ostream &out, Game &g);
};